### ISSUE TITLE
How can get PyCeresIK ?

### ISSUE THREAD

**Issue by StephenLee2016** [FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18#1]
Thanks for your excellent job! But where can i get PyCeresIK package?

**Comment by padeler** [comment]
I just updated the README with links. We just released this code and we will be adding more in the next days.

**Comment by Vincent-2017** [comment]
I have the same question....

**Comment by padeler** [comment]
Follow the instructions [here](https://github.com/FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18/blob/master/lib/README.md) to download the library and setup your environment.
