### ISSUE TITLE
ModuleNotFoundError: No module named 'PyJointTools'

### ISSUE THREAD

**Issue by Jalpa119** [FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18#11]
I am not able to find out PyJointTools module. 

i  am using windows 10 and python 3.6 

Not sure how to install above module. Any help appreciate . 
Thank you in Advance.

**Comment by padeler** [comment]
We provide linux binaries for this module. You will have to test it on a linux system. 
Currently we have no plans for supporting windows.

**Comment by Jalpa119** [comment]
Now i am working on linux machine . But still no idea how to install PyJointTools library. 

NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

python3.6

**Comment by padeler** [comment]
Your system setup is fine. 

Just follow the [instructions](https://github.com/FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18/blob/master/lib/README.md). You will need to download the libraries package (PyJointTools etc) from the provided link and update your LD_LIBRARY_PATH environment variable to contain the folder with the libraries.
