### ISSUE TITLE
How to test the youtube vedio without the camera parameters?

### ISSUE THREAD

**Issue by Vincent-2017** [FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18#13]
Thank you for your codes! If I want to use the youtube vedio, what should I do without the camera parameters?

**Comment by padeler** [comment]
If you don't know the camera parameters for your video, just modify the supplied json calib file with some plausible values. It will not be the optimum, but you can get decent results with a little experimentation. 

This is how I tracked the qualitative video with the PMJ song. 

Of-course best results will require proper camera calibration.
