### ISSUE TITLE
freeglut (c): ERROR: Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow

### ISSUE THREAD

**Issue by StephenLee2016** [FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18#2]
Hi, When i run handpose.py script met "freeglut (c): ERROR: Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow" error

**Comment by padeler** [comment]
It looks like an issue with glut. You need to have freeglut3 installed. Can you give more details on your system? GPU driver, CUDA version

**Comment by StephenLee2016** [comment]
> It looks like an issue with glut. You need to have freeglut3 installed. Can you give more details on your system? GPU driver, CUDA version

Yes, you're right. I reinstall freeglut and the error gone. Another question, if the pyceresik.so could be used in android？

**Comment by padeler** [comment]
PyCeresIK computes the inverse kinematics of the hand and it is built around Ceres. Ceres can run on android and our method for IK could be adapted to build with the android NDK. 

So yes it is possible to port this project to android but it is not trivial.

**Comment by StephenLee2016** [comment]
> PyCeresIK computes the inverse kinematics of the hand and it is built around Ceres. Ceres can run on android and our method for IK could be adapted to build with the android NDK.
> 
> So yes it is possible to port this project to android but it is not trivial.


Hello, I am very interested in this scene about PyCeresIK
, so can you tell more implementation details, or can share my your script?

**Comment by padeler** [comment]
The PyCeresIK library is based on the [Ceres solver](http://ceres-solver.org/) and performs the IK step of our method. 

We have no plans to make it opensource right now.
