### ISSUE TITLE
Can I implement this project on centos system?

### ISSUE THREAD

**Issue by MLsmaller** [FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18#3]
hello,I'm very interested in this project.you provide Ubuntu 16.04 binaries for these libraries.Could you please tell me whether centos7 system can realize this project? I could not download the project when I relied on it according to the instructions.
By the way ,when I run the script,the error is :
![image](https://user-images.githubusercontent.com/40620409/55954680-ec8a2300-5c91-11e9-80ac-0d3d610825e3.png)

I don't know what that means.I sincerely hope to get your reply

**Comment by padeler** [comment]
Hello,

We only provide binaries for ubuntu 16.04. Our code can run on other OSes but it is a big overhead to provide binaries and support for many different systems.

The error you get is due to missing boost v1.58 libraries. You could download build and install the boost library 1.58 in your centos ( and possibly other missing libraries). In ubuntu 16.04 it is available as a system package.

**Comment by MLsmaller** [comment]
> Hello,
> 
> We only provide binaries for ubuntu 16.04. Our code can run on other OSes but it is a big overhead to provide binaries and support for many different systems.
> 
> The error you get is due to missing boost v1.58 libraries. You could download build and install the boost library 1.58 in your centos ( and possibly other missing libraries). In ubuntu 16.04 it is available as a system package.
Doesn't PyCeresIk need to be downloaded by itself? Is it already in Python?

**Comment by padeler** [comment]
We provide PyCeresIK along with other libraries. Follow the instructions [here](https://github.com/FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18/blob/master/lib/README.md)

**Comment by MLsmaller** [comment]
> We provide PyCeresIK along with other libraries. Follow the instructions [here](https://github.com/FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18/blob/master/lib/README.md)

Thanks a lot.Could you please tell me if I acquire the keypoints of hands through my own model and then can I acquire the 3D hand pose via non-linear least squares squares fits a 3D model of the hand to the estimated 2D joint positions and recovering the 3D hand pose? 
Because I want to get a 3d model of my hand, but my system is centos7, I may not be able to run this model. If this method is feasible, I should look at which part of the code I input my keypoints to get the 3d model. I sincerely hope to get your reply.

**Comment by padeler** [comment]
Yes you can use your own 2D joint estimator. 

Check the supplied example python scripts. I provide 2 versions one is using openpose and the other is using our work  (Gouidis et al) for 2D joints.

**Comment by MLsmaller** [comment]
> Yes you can use your own 2D joint estimator.
> 
> Check the supplied example python scripts. I provide 2 versions one is using openpose and the other is using our work (Gouidis et al) for 2D joints.

My running code reports an error in the step of import PyCeresIK as Ik. Is it possible for me to run this project on centos7 system? 
![image](https://user-images.githubusercontent.com/40620409/56073675-a4c2e300-5dda-11e9-9749-0cb56cc9456a.png)

Whether PyCeresIK library cannot be imported on centos system, or relevant dependencies need to be downloaded, could you please give me some instructions? Thank you

**Comment by MLsmaller** [comment]
I compiled and installed boost v1.58 libraries. This error is now running. I did not find this file on the system.
![image](https://user-images.githubusercontent.com/40620409/56073902-dd63bc00-5ddc-11e9-9006-120e5ab6bfd0.png)

Whether PyCeresIK library cannot be imported on centos system, or relevant dependencies need to be downloaded? If possible, could you give me some guidance? Thank you very much.

**Comment by padeler** [comment]
When you build boost from source the boost-python libraries have a different name. You will need to create  the correct symbolic links to libboost_python-py35.so.1.58.0

I am sorry but I cannot provide further support for CentOS.

**Comment by StephenLee2016** [comment]
> When you build boost from source the boost-python libraries have a different name. You will need to create the correct symbolic links to libboost_python-py35.so.1.58.0
> 
> I am sorry but I cannot provide further support for CentOS.

Hi， Prof. Padeler

I sent an email to your trahania@ics.forth.gr mailbox, can you check it? Thanks

**Comment by padeler** [comment]
Hello, 

That is not my mail. 
Please post questions here so other people can benefit from the discussion.

thanks

**Comment by StephenLee2016** [comment]
> Hello,
> 
> That is not my mail.
> Please post questions here so other people can benefit from the discussion.
> 
> thanks

Hi，


I want to know if you can cooperate with our organization or buy your commercial authorization. If you can, please leave your contact details for further details.


Thanks

**Comment by padeler** [comment]
You can contact me or any other of the authors of the paper at the addresses stated [here](http://users.ics.forth.gr/~argyros/mypapers/2018_03_WACV_rgbmonohand.pdf).
