### ISSUE TITLE
hand detection

### ISSUE THREAD

**Issue by shajie17** [FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18#6]
Can you provide code and models for hand detection?

**Comment by padeler** [comment]
Hello,

The hand-detection module was built on a different code-base which we do not have plans to make public currently. However the hand detector was based on a yolo v2 net (pretrained on imagenet) retrained to detect hands and faces. It should be relative simple to re implement. 

best,
--
pashalis
