### ISSUE TITLE
ImportError: dynamic module does not define init function (initPyCeresIK)

### ISSUE THREAD

**Issue by gstavrinos** [FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18#8]
Hello,

After having installed all the required dependencies and libraries, I try to run the handpose.py script by just running `python handpose.py`, but I receive the error in the title.

I am using Ubuntu 16.04 and Python2.7.

Any suggestions?

Thanks in advance,

George

**Comment by padeler** [comment]
You need python3 to run the demo.

**Comment by gstavrinos** [comment]
Thanks for the answer. I got confused, because in PyOpenPose, Python2 seemed the default one, since a flag was needed to compile for python3.
